p File.join("a/", "b")
p File.join("a", "", "b")
p File.join("a", "/b")
p File.join("", "a")
p File.join("a//", "b")
p File.join("a//", "//b")
p File.join(["a", "b"], "c")
p File.join("a", ["b", ["c"]])
p File.basename("/a/b/")
p File.basename("/")
p File.basename("a/b//")
p File.basename("///")
p File.basename("")
p File.basename("b")
p File.basename("/a/b/c.rb", ".rb")
p File.basename("/a/b/c.rb", ".*")
p File.basename("c.tar.gz", ".*")
p File.basename("c.rb", ".py")
File.write("/tmp/sp_file_zero_empty_#{Process.pid}.txt", "")
p File.size("/tmp/sp_file_zero_empty_#{Process.pid}.txt")
p File.zero?("/tmp/sp_file_zero_empty_#{Process.pid}.txt")
p File.empty?("/tmp/sp_file_zero_empty_#{Process.pid}.txt")
File.delete("/tmp/sp_file_zero_empty_#{Process.pid}.txt")
p File.zero?("/tmp")
p File.zero?("/dev/null")
p File.zero?("/nonexistent_zzz")
r = (File.exists?("/tmp") rescue $!.class); p r
r2 = (Dir.exists?("/tmp") rescue $!.class); p r2
p File::ALT_SEPARATOR
p File::ALT_SEPARATOR.nil?
