# The pure-path half of Pathname: manipulation that never touches the disk,
# so it answers for paths that do not exist. Every expectation here is
# CRuby's own output.
require "pathname"
P = Pathname
show = ->(label, v) { puts "#{label} => #{v.inspect}" }
show.("plus rel",   (P.new("/a") + "b"))
show.("plus abs",   (P.new("/a") + "/b"))
show.("plus dotdot",(P.new("a/b") + ".."))
show.("plus dot",   (P.new("a") + "."))
show.("plus trailing", (P.new("a") + "b/"))
show.("plus dot slash", (P.new("a") + "./"))
show.("plus dotdot slash", (P.new("a") + "../"))
show.("plus up slash", (P.new("a/b") + "../../"))
show.("plus past slash", (P.new("a/b") + "../../../"))
show.("plus root slash", (P.new("/") + "b/"))
show.("slash",      (P.new("/a") / "b" / "c"))
show.("join",       P.new("/a").join("b", "c"))
show.("parent abs", P.new("/a/b").parent)
show.("parent rel", P.new("a").parent)
show.("parent root",P.new("/").parent)
show.("dirname",    P.new("/a/b.txt").dirname)
show.("basename",   P.new("/a/b.txt").basename)
show.("basename x", P.new("/a/b.txt").basename(".txt"))
show.("extname",    P.new("/a/b.txt").extname)
show.("sub_ext",    P.new("/a/b.txt").sub_ext(".md"))
show.("sub_ext none",P.new("/a/b").sub_ext(".md"))
show.("root? y",    P.new("/").root?)
show.("root? n",    P.new("/a").root?)
show.("abs?",       P.new("/a").absolute?)
show.("rel?",       P.new("a").relative?)
show.("clean1",     P.new("a/./b/../c").cleanpath)
show.("clean2",     P.new("/a//b/").cleanpath)
show.("clean3",     P.new("..").cleanpath)
show.("clean4",     P.new("").cleanpath)
show.("split",      P.new("/a/b").split)
show.("each_filename", P.new("/a/b/c").each_filename.to_a)
show.("descend",    P.new("/a/b").descend.to_a)
show.("ascend",     P.new("/a/b").ascend.to_a)
show.("relpath",    P.new("/a/b/c").relative_path_from(P.new("/a")))
show.("relpath up", P.new("/a/x").relative_path_from(P.new("/a/b/c")))
show.("cmp",        (P.new("/a") <=> P.new("/b")))
show.("eq",         P.new("/a") == P.new("/a"))
show.("to_s",       P.new("/a").to_s)
show.("inspect",    P.new("/a"))
show.("sort",       [P.new("/b"), P.new("/a")].sort)
show.("empty str",  P.new(""))
